## NumPy useful functions

#### np.sort() -> it returns the sorted copy of an array

In [1]:
# importing libraries
import numpy as np

In [ ]:
# creating 1 D array
a = np.random.randint(1,100,15)
a

array([37, 61,  8, 26,  8,  6, 96, 56, 71, 55, 10, 91, 27, 99,  7])

In [5]:
# creating 2 D array
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 40, 50, 58],
       [38, 82, 73, 53],
       [82, 99, 62, 84],
       [79, 64, 16, 32],
       [54, 78, 25, 69],
       [99, 65, 38, 93]])

#### Sorting in 1 D array

In [6]:
np.sort(a)

array([ 6,  7,  8,  8, 10, 26, 27, 37, 55, 56, 61, 71, 91, 96, 99])

#### Sorting in 2 D array

In [7]:
np.sort(b)

array([[40, 50, 51, 58],
       [38, 53, 73, 82],
       [62, 82, 84, 99],
       [16, 32, 64, 79],
       [25, 54, 69, 78],
       [38, 65, 93, 99]])