## NumPy useful functions

#### np.sort() -> it returns the sorted copy of an array

In [1]:
# importing libraries
import numpy as np

In [91]:
# creating 1 D array
a = np.random.randint(1,100,15)
a

array([21, 68, 97, 31, 84, 27, 32,  6, 20, 88, 86, 63,  1, 26, 98])

In [5]:
# creating 2 D array
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 40, 50, 58],
       [38, 82, 73, 53],
       [82, 99, 62, 84],
       [79, 64, 16, 32],
       [54, 78, 25, 69],
       [99, 65, 38, 93]])

#### Sorting in 1 D array

In [6]:
np.sort(a)

array([ 6,  7,  8,  8, 10, 26, 27, 37, 55, 56, 61, 71, 91, 96, 99])

#### Sorting in 2 D array

In [8]:
# this will sort row wise
np.sort(b)

# if we want to sort column wise use axis=0

np.sort(b,axis=0)

array([[38, 40, 16, 32],
       [51, 64, 25, 53],
       [54, 65, 38, 58],
       [79, 78, 50, 69],
       [82, 82, 62, 84],
       [99, 99, 73, 93]])

#### np.append() -> add / append the value along the mentioned axis at the end of the array

#### Appending in 1 D array

In [30]:
# appending item in array
np.append(a,12)

array([37, 61,  8, 26,  8,  6, 96, 56, 71, 55, 10, 91, 27, 99,  7, 12])

#### Appending in 2 D array

In [15]:
# appending a new column at the end of the 2 D array b and reshaping it into 6,5 
np.append(b,np.ones((b.shape[0],1))).reshape(6,5)

array([[51., 40., 50., 58., 38.],
       [82., 73., 53., 82., 99.],
       [62., 84., 79., 64., 16.],
       [32., 54., 78., 25., 69.],
       [99., 65., 38., 93.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### np.concatenate() -> it concatenate a sequence of arrays along an existing values

In [17]:
# creating array
c = np.arange(6).reshape(2,3)
d = np.arange(6).reshape(2,3)

In [22]:
# concatenating c and d
# row wise
np.concatenate((c,d),axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [23]:

# column wise
np.concatenate((c,d),axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

### np.unique() -> we can get unique values from our array given as a parameter in np.unique() method

In [26]:
# creating array
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([1,2,3,1,2,3,2])

print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[1 2 3 1 2 3 2]


In [28]:
# using unique function from e
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [31]:
# using unique function from f
np.unique(f)

array([1, 2, 3])

### np.expand_dims() -> we can get the expanded dimensions of an array

In [34]:
np.expand_dims(f,axis=1)

array([[1],
       [2],
       [3],
       [1],
       [2],
       [3],
       [2]])

### np.where() -> it returns the indices of elements in an input array where the given condition is satisfied  

In [37]:
# returns the index position all the elemets whose value is greater than 50
np.where(a>50)

(array([ 1,  6,  7,  8,  9, 11, 13]),)

In [39]:
# now replace all the values > 50 with 0
# syntax .where(contion, true, false) -> (condtion, then agr condition true h to ky krna h, false h to ky krna h)

np.where(a>50,0,a)

array([37,  0,  8, 26,  8,  6,  0,  0,  0,  0, 10,  0, 27,  0,  7])

In [41]:
# replace all the even numbers with 0 in array a
np.where(a%2==0,0,a)

array([37, 61,  0,  0,  0,  0,  0,  0, 71, 55,  0, 91, 27, 99,  7])

In [42]:
# replace all the odd numbers with 1 and even with 0
np.where(a%2!=0,1,0)

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1])

#### np.agrmax() -> it returns the index of the max element of the array in a particular axis

In [48]:
# find at which index position the largest number is present
print(a)
print(np.argmax(a))

[37 61  8 26  8  6 96 56 71 55 10 91 27 99  7]
13


In [51]:
# 2 D array
# column wise
print(b)
np.argmax(b,axis=0)

[[51 40 50 58]
 [38 82 73 53]
 [82 99 62 84]
 [79 64 16 32]
 [54 78 25 69]
 [99 65 38 93]]


array([5, 2, 1, 5])

In [52]:
# 2 D array
# row wise
print(b)
np.argmax(b,axis=1)

[[51 40 50 58]
 [38 82 73 53]
 [82 99 62 84]
 [79 64 16 32]
 [54 78 25 69]
 [99 65 38 93]]


array([3, 1, 1, 0, 1, 0])

#### np.argmin() -> it returns the index of the min element of the array in a particular axis

In [53]:
np.argmin(a)

np.int64(5)

### np.cumsum() -> used when we want to compute the comulative sum of array elements over a given axis

In [55]:
# cumsum means -> cumulative sum (current wale m picli value add)
# 1 D array
np.cumsum(a)

array([ 37,  98, 106, 132, 140, 146, 242, 298, 369, 424, 434, 525, 552,
       651, 658])

In [57]:
# 2 D array
np.cumsum(b)

# if we want to find the cumulative sum of any particular row or column use axis=0 or 1

array([  51,   91,  141,  199,  237,  319,  392,  445,  527,  626,  688,
        772,  851,  915,  931,  963, 1017, 1095, 1120, 1189, 1288, 1353,
       1391, 1484])

### cumprod()

In [59]:
# 1D array
np.cumprod(a)

array([                  37,                 2257,                18056,
                     469456,              3755648,             22533888,
                 2163253248,         121142181888,        8601094914048,
            473060220272640,     4730602202726400,   430484800448102400,
       -6823654461610786816,  6987739027785515008, -6426059026630049792])

In [60]:
# 2D array
np.cumprod(b)

array([                  51,                 2040,               102000,
                    5916000,            224808000,          18434256000,
              1345700688000,       71322136464000,     5848415190048000,
         578993103814752000,  -995915710904479232,  8576800652571502592,
       -4962279174104705024, -3991217889638744064, -8519254013091250176,
        4085032686723268608,  -769163801458114560, -4654544292604280832,
       -5683142872849711104, -4755232678729482240,  8847310722229600256,
        3226130659927916544, -6534243438706032640,  1057914632754167808])

### np.percentile() -> this function is used to find the nth percentile of the given data (array elements) along the specific axis

In [64]:
# 1D array
# here 100 percentile is maximum and 0 percentile is minimum
# maximum percentile
np.percentile(a,100)

np.float64(99.0)

In [66]:
# mimimum percentile
np.percentile(a,0)

np.float64(6.0)

### np.histogram() -> it shows the frequency of data distribution in the graphical form

In [69]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([4, 1, 2, 1, 0, 2, 1, 1, 0, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef() -> returns pearson product moment correlation coefficients

In [71]:
# creating array
salary = np.array([20000,40000,25000,35000,60000])
experince = np.array([1,3,2,4,2])

# funtion
np.corrcoef(salary,experince)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin()

In [75]:
# creating arrays
items = [10,20,30,40,50,60,70,80,90]

np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

### np.flip() -> reverse the order of the elements of the array along the specified axis

In [78]:
# this will flip (reverse) the array
# 1D aray
np.flip(a)

array([ 7, 99, 27, 91, 10, 55, 71, 56, 96,  6,  8, 26,  8, 61, 37])

In [79]:
# 2D array
np.flip(b)

array([[93, 38, 65, 99],
       [69, 25, 78, 54],
       [32, 16, 64, 79],
       [84, 62, 99, 82],
       [53, 73, 82, 38],
       [58, 50, 40, 51]])

### np.put() -> it replaces specific elements of an array with given value of p_array

In [90]:
print(a)

None


In [ ]:
np.put(a, [0, 1], [110, 530])

### np.delete()

In [93]:
np.delete(a,0)

array([68, 97, 31, 84, 27, 32,  6, 20, 88, 86, 63,  1, 26, 98])

### Sets Functions

In [94]:
# creating array
m = np.array([1,2,3,4,5])
n = np.array([6,7,8,9,10])

In [96]:
# union
np.union1d(1,b)

array([ 1, 16, 25, 32, 38, 40, 50, 51, 53, 54, 58, 62, 64, 65, 69, 73, 78,
       79, 82, 84, 93, 99])

In [101]:
# intersection
np.intersect1d(m,n)

array([], dtype=int64)

In [102]:
# set difference
np.setdiff1d(m,n)

array([1, 2, 3, 4, 5])

In [105]:
# setxor
np.setxor1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### np.clip() -> used to clip (limit) the values in an array

In [106]:
np.clip(a,a_min=25,a_max=75)

array([25, 68, 75, 31, 75, 27, 32, 25, 25, 75, 75, 63, 25, 26, 75])